Bump MarkupSafe to 1.1.1 in requirements.txt to fix setuptools issue
As of 21 March 2021 running `make build` on the default branch of this
repository breaks with the following error:

```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bfkg7hzw/markupsafe_2ff6d76a552d4703960c9f49f15673c8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bfkg7hzw/markupsafe_2ff6d76a552d4703960c9f49f15673c8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hn261ajv
         cwd: /tmp/pip-install-bfkg7hzw/markupsafe_2ff6d76a552d4703960c9f49f15673c8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bfkg7hzw/markupsafe_2ff6d76a552d4703960c9f49f15673c8/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from https://pypi.org/simple/markupsafe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0
ERROR: No matching distribution found for MarkupSafe==1.0
```

There is a Closed issue logged in the MarkupSafe repository,
pallets/markupsafe#116 where a maintainer explained upgrading shouldn't
have any compatibility issues.

So the MarkupSafe requirement has been set to 1.1.1